### ISSUE TITLE
Migrate away from using 'add-path'

### ISSUE THREAD

**Issue by pjoe** [pulumi/action-install-pulumi-cli#7]
Getting following error:
```
Error: The `add-path` command is deprecated and will be disabled on November 16th.
Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

See: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by stack72** [comment]
Hi @pjoe 

This has been fixed via 59780a25b75ef714621d632455e1f30b788730b5

**Comment by pjoe** [comment]
Sweet, that was a quick response 🙏

**Comment by axwalker** [comment]
I still get the following error this morning:

```
Run pulumi/action-install-pulumi-cli@releases/v1
/bin/tar xz -C /home/runner/.pulumi -f /home/runner/work/_temp/795962c3-fbeb-4881-af7d-3a270cd2b514
Error: Unable to process command '::add-path::/home/runner/.pulumi/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by stack72** [comment]
Hi @axwalker 

I published v1.0.1 to the marketplace and don't get any errors

Can you check that version?

**Comment by axwalker** [comment]
When I try to use v1.0.1 with:

```
- uses: pulumi/action-install-pulumi-cli@releases/v1.0.1
```

I get:

```
Unable to resolve action `pulumi/action-install-pulumi-cli@releases%2Fv1.0.1`, unable to find version `releases/v1.0.1`
```

Is this not how I specify that version?

**Comment by stack72** [comment]
You no longer need releases/ - that's a change to how gha works

This is the code snippet that the marketplace shows now - https://github.com/marketplace/actions/install-pulumi-cli?version=v1.0.1

- name: Install Pulumi CLI
  uses: pulumi/action-install-pulumi-cli@v1.0.1

**Comment by axwalker** [comment]
Ah, that page still shows `uses: pulumi/action-install-pulumi-cli@releases/v1` for me. Unless I click the button in the top right saying 'Use latest version', then I get a popup with the new format.

I've pushed this now and will let you know if it works. Thanks!

**Comment by axwalker** [comment]
@stack72 cool, that works fine now. Thanks a lot for your quick response!

Perhaps it's worth updating the readme for this repo with the new format? That's where I'd copied from (I wasn't previously using this action at all until today - I'd been installing pulumi myself)

**Comment by stack72** [comment]
ah my apologies here - I will get this fixed up right now!

**Comment by roderik** [comment]
FYI, in the platform when setting up a new stack, the template you can copy still has the old version

**Comment by stack72** [comment]
Hi @roderik 

What do you mean? Are you referring to the version in the README or somewhere else?

Paul

**Comment by stack72** [comment]
Ping @roderik

**Comment by roderik** [comment]
Here: 
![CleanShot 2020-12-21 at 16 40 22@2x](https://user-images.githubusercontent.com/16780/102794178-43268a80-43ab-11eb-8a45-ad6bc6364909.png)

**Comment by stack72** [comment]
Oh I see! thank you - that's super useful to get the screenshot of - I will work with the service team to get this fixed

**Comment by praneetloke** [comment]
Thanks, @roderik! I have opened https://github.com/pulumi/ci-workflow-templates/issues/5.
